config/routes.rb
Rails.application.routes.draw do
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord

  validates :price, numericality: { greater_than: 0, allow_nil: true }
  validates :name, presence: true

  # Callbacks
  after_initialize { p 'initialize' } #Item.new Item.first
  after_save       { p 'save' } #Item.create Item.save
  after_create     { p 'create' } #Item.create
  after_update     { p 'update' } #Item.update
  after_destroy    { p 'destroy' } #Item.last.after_destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  layout false
  skip_before_action :verify_authenticity_token

  def index # Показывает все что есть в базе данных
    @items = Item.all
      render body: @items.map { |i| "#{i.name}: #{i.price}"}
  end

  def create # Создает обьект в базу
    item = Item.create(items_params)
    if item.persisted?
      render json: item.name, status: :created
    else
      render json: item.errors, status: :unprocessable_entity
    end
  end

  def new # Рендерит форму и посылается методу create
   # создаем новый объект модели item и присваиваем его переменной экземпляра
  end

  def show # Показыает item по текущему id
  end

  def edit # При вызове метода edit он будет посылатся на метод update
  end

  def update # Обновляет обьект в базе данных
  end

  def destroy # Удаляет обьект с базы данных
  end

  private

  def items_params
    params.permit(:name, :price, :real, :weight, :description,)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h2 style="color: #B00100; margin: 0 auto">Edit item</h2>

<%= form_tag edit_item_path, method: :get do %>
  <%= label_tag :name %>
  <%= text_field_tag :name %>
  <%= label_tag :price %>
  <%= text_field_tag :price %>
  <%= submit_tag "Save", class: "btn btn-large btn-primary" %>
<% end %>

app/views/items/index.html.erb
<% @items.each do |item| %>
   <ul> %>
     <li><%= item.name %></li>
     <li><%= item.price %></li>
     <li><%= item.description %></li>
   </ul>
<% end %>

app/views/items/new.html.erb
<h2 style="color: #B00100; margin: 0 auto">Create new item</h2>


<%= form_tag items_path, method: :post do %>
  <%= label_tag :name %>
  <%= text_field_tag :name %>
  <%= label_tag :price %>
  <%= text_field_tag :price %>
  <%= submit_tag "Save", class: "btn btn-large btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>